### ISSUE TITLE
Ask user for file to write RFC to with menu

### ISSUE THREAD

**Issue by anirudhRowjee** [anirudhRowjee/py-getrfc#6]
self-explanatory.

**Comment by anirudhRowjee** [comment]
Sure!

**Comment by prishagoel** [comment]
Hi, I went through the code, and it appears as though the code never runs the tofile part because of which whenever there is no file name, no new file is being created

**Comment by anirudhRowjee** [comment]
So when the user chooses to write an RFC to a file, you'll need to take input from them in some form to know the location and filename to dump the RFC into.
